# Generated by Django 4.2.1 on 2023-07-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dropdown',
            options={},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={},
        ),
        migrations.RemoveField(
            model_name='dependent',
            name='account',
        ),
        migrations.RemoveField(
            model_name='dropdown',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='form',
            name='account',
        ),
        migrations.RemoveField(
            model_name='form',
            name='address',
        ),
        migrations.RemoveField(
            model_name='form',
            name='age',
        ),
        migrations.RemoveField(
            model_name='form',
            name='district',
        ),
        migrations.RemoveField(
            model_name='form',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='form',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='form',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='form',
            name='number',
        ),
        migrations.AddField(
            model_name='dependent',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dependent',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dependent',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dependent',
            name='gender',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AddField(
            model_name='dependent',
            name='mail',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AddField(
            model_name='dependent',
            name='name',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AddField(
            model_name='dependent',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dropdown',
            name='name',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(default=True, max_length=250),
        ),
    ]
