# Generated by Django 4.2.1 on 2023-07-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0002_alter_dependent_options_alter_dropdown_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='gender',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='mail',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dropdown',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
