# Generated by Django 4.2.1 on 2023-07-27 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0003_alter_dependent_gender_alter_dependent_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Down',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='dependent',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankingapp.form'),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankingapp.dropdown'),
        ),
        migrations.AddField(
            model_name='dependent',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankingapp.down'),
        ),
    ]
