# Generated by Django 4.2.1 on 2023-07-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0004_down_dependent_district_alter_dependent_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='cheque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='debit',
            field=models.BooleanField(default=False),
        ),
    ]
