# Generated by Django 4.2.1 on 2023-07-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0005_alter_dependent_cheque_alter_dependent_credit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Drop',
        ),
    ]
